#### 1차원은 벡터 , 2차원은 매트릭스 , 3차원부터 텐서

- 딥러닝에서는 텐서가 매우 중요
- 2D Tensor(Typical Simple Setting) 
-  |t| = (batch size, dim)


- 3D Tensor(TypicalComputer Vision)
-  |t| = (batch size(높이) , width(가로) , height(세로))


- 3D Tensor(Typical NLP)
- |t| = (batch size , length ,dim)


#### NumPy Review

In [1]:
import numpy as np
t= np.array([0. ,1. ,2., 3., 4., 5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [2]:
print('Rank of t:', t.ndim)
print('shape of t:',t.shape)

Rank of t: 1
shape of t: (7,)


In [3]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1] = ',t[2:5] , t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [4]:
import torch

In [5]:
t= torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])


1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [7]:
m1= torch.FloatTensor([[3,3]])
m2= torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [8]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])  # [3]-> [[3,3]]  Broadcasting
print(m1+m2)

tensor([[4., 5.]])


In [10]:
#2x1 vector + 1x2 vector
m1 = torch.FloatTensor([[1,2]])
m2= torch.FloatTensor([[3],[4]])  
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [16]:
# View(Reshape)
t= np.array([[[0,1,2],[3,4,5],[6,7,8]],  [[6,7,8],[9,10,11],[12,13,14]]])
ft = torch.FloatTensor(t)
print(ft.shape)


torch.Size([2, 3, 3])


In [17]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
torch.Size([6, 3])


In [18]:
ft = torch.FloatTensor([[0],[1],[3]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [3.]])
torch.Size([3, 1])


In [20]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 3.])
torch.Size([3])
